name: deploy-book

on: [push]

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  marimo:
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    steps:
      - uses: jebel-quant/marimushka@v0.1.2
        with:
          notebooks: 'notebooks'

