name: deploy-book

on:
  push:
    branches:
      - main

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  marimo:
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    steps:
      - uses: jebel-quant/marimushka@v0.1.2
        with:
          notebooks: 'notebooks'
          notebooks_wasm: 'notebooks'

  book:
    runs-on: "ubuntu-latest"
    needs: [ marimo ]

    environment:
      name: github-pages  # 👈 this is the critical missing piece

    permissions:
      pages: write            # Permission to deploy to Pages
      id-token: write         # Permission to verify deployment origin

    steps:
      - uses: tschm/cradle/actions/book@v0.1.75
        with:
          title: "Quaternion"
          links: |
            {
              "Notebooks": "./marimushka/index.html"
            }
